#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-A-0 -d 1 2 3
bspc monitor DVI-D-0  -d 4 5 6

bspc config normal_border_color  "#32302f"
bspc config active_border_color "#32302f"
bspc config focused_border_color "#d4be98"

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Steam desktop='^2'
bspc rule -a discord desktop='^5'

# Launch Picom
picom &

# Set Wallpapers
xwallpaper --output HDMI-A-0 --center ~/.local/share/wallpaper.jpg
xwallpaper --output DVI-D-0 --center ~/.local/share/wallpaper.jpg

# Launch Polybar
$HOME/.config/polybar/launch.sh

# Launch Dunst
dunst &
