#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-A-0 -d 1 2 3
bspc monitor DVI-D-0  -d 4 5 6

bspc config normal_border_color  "#303336"
bspc config active_border_color "#828482"
bspc config focused_border_color "#c5c8c6"

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Steam desktop='^2'
bspc rule -a firefox desktop='^4'
bspc rule -a discord desktop='^5'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Launch Picom
picom &

# Set Wallpaper
~/.fehbg &

# Launch Polybar
$HOME/.config/polybar/launch.sh

# Launch Dunst
dunst &
